spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cosmetology
    username: postgres
    password: docker
server:
  error:
    include-message:always
    include-binding-errors:always

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: public

  liquibase:
    change-log: "classpath:db/changelog/changelog.xml"
    enabled: false
