spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cosmetology
    username: postgres
    password: docker
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: public
